[package]
name = "ijson-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.ijson]
path = ".."

[[bin]]
name = "fuzz_tests"
path = "fuzz_targets/fuzz_tests.rs"
test = false
doc = false
bench = false
